=== impresso/impresso-schemas/json/return_card/enrichments.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://impresso.github.io/impresso-schemas/json/return_card/enrichments.schema.json",
    "description": "A representation of the semantic enrichments for for a alias-year pair.",
    "title": "Impesso Semantic Enrichments",
    "type": "object",
    "properties": {
        "alias_year_key": {
            "type": "string",
            "description": "Impresso alias and year to which these enrichments correspnd (eg. `GDL-1900`)",
            "pattern": "^[A-Za-z][A-Za-z0-9_]*-\\d{4}$"
        },
        "timestamp": {
            "type": "string",
            "description": "Creation date timestamp (in '%Y-%m-%dT%H:%M:%SZ' format).",
            "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$"
        },
        "partner_institution": {
            "type": "string",
            "description": "Internal alias corresponding to the partner institution this CI comes from."
        },
        "impresso_data": {
            "type": "object",
            "description": "All the S3 paths to the corresponding objects and enrichments in the Impresso data.",
            "properties": {
                "prepared_data": {
                    "type": "array",
                    "description": "The data stages and S3 paths corresponding to the prepared data for this CI.",
                    "items": {
                        "description": "The name and corresponding S3 path of this CI's data representation or enrichment.",
                        "$ref": "#/$defs/impresso_s3_paths"
                    }
                },
                "semantic_enrichments": {
                    "type": "array",
                    "description": "The semantic enrichments and their s3 paths for this CI.",
                    "items": {
                        "description": "A content item (e.g. article, advertisement, radio broadcast, etc.)",
                        "$ref": "#/$defs/impresso_s3_paths"
                    }
                }
            },
            "required": [
                "prepared_data"
            ]
        }
    },
    "$defs": {
        "impresso_s3_paths": {
            "type": "object",
            "properties": {
                "datastage_name": {
                    "type": "string",
                    "description": "Name of the data stage or enrichment linked.",
                    "enum": [
                        "canonical-issues",
                        "canonical-pages",
                        "canonical-audios",
                        "rebuilt",
                        "emb-words",
                        "emb-docs",
                        "emb-entities",
                        "emb-sents",
                        "emb-images-clip",
                        "emb-images-dino",
                        "entities",
                        "newsagencies",
                        "langident",
                        "lingproc",
                        "ocrqa",
                        "textreuse-passages",
                        "textreuse-clusters",
                        "textreuse-index",
                        "topic-assignments",
                        "topics"
                    ]
                },
                "datastage_schema_link": {
                    "type": "string",
                    "description": "GitHub Link to the datastage's JSON schema."
                },
                "s3_path": {
                    "type": [
                        "string",
                        "array"
                    ],
                    "description": "S3 URL (or list of urls) to the data or enrichment with this CI (e.g. `s3://112-canonical-final/LeTemps/GDL/issues/GDL-1900-issues.jsonl.bz2` for canonical issues)."
                }
            }
        }
    },
    "required": [
        "alias_year_key",
        "timestamp",
        "partner_institution",
        "impresso_data"
    ]
}

=== impresso/impresso-schemas/examples/return_card/BELL-1855-enrichments.json
{
    "alias_year_key": "BELL-1855",
    "timestamp": "2025-10-09T09:53:17Z",
    "partner_institution": "BL",
    "impresso_data": {
        "prepared_data": [
            {
                "datastage_name": "canonical-issues",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/canonical/issue.schema.json",
                "s3_path": "s3://112-canonical-final/BL/BELL/issues/BELL-1855-issues.jsonl.bz2"
            },
            {
                "datastage_name": "canonical-pages",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/canonical/page.schema.json",
                "s3_path": "s3://112-canonical-final/BL/BELL/pages/BELL-1855/BELL-1855-05-12-a-pages.jsonl.bz2"
            }
        ],
        "semantic_enrichments": [
            {
                "datastage_name": "emb-words",
                "datastage_schema_link": "TODO",
                "s3_path": "s3://42-processed-data-final/embeddings/words/legacy-wemb002/"
            },
            {
                "datastage_name": "textreuse-clusters",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/text_reuse/cluster.schema.json",
                "s3_path": "s3://42-processed-data-final/textreuse/textreuse_passim_v1-0-0/results/tr_clusters/"
            },
            {
                "datastage_name": "topics",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/topic_model/topic_description.schema.json",
                "s3_path": [
                    "s3://42-processed-data-final/topics/topics-tm-mallet_infer_seed42_v2.0.1-multilingual_v2-0-1/tm-de-all-v2.0.topic_model_topic_description.jsonl.bz2",
                    "s3://42-processed-data-final/topics/topics-tm-mallet_infer_seed42_v2.0.1-multilingual_v2-0-1/tm-fr-all-v2.0.topic_model_topic_description.jsonl.bz2",
                    "s3://42-processed-data-final/topics/topics-tm-mallet_infer_seed42_v2.0.1-multilingual_v2-0-1/tm-lb-all-v2.1.topic_model_topic_description.jsonl.bz2"
                ]
            }
        ]
    }
}

=== impresso/impresso-schemas/examples/return_card/lepji-1889-enrichments.json
{
    "alias_year_key": "lepji-1889",
    "timestamp": "2025-10-09T09:50:55Z",
    "partner_institution": "BNF",
    "impresso_data": {
        "prepared_data": [
            {
                "datastage_name": "canonical-issues",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/canonical/issue.schema.json",
                "s3_path": "s3://112-canonical-final/BNF/lepji/issues/lepji-1889-issues.jsonl.bz2"
            },
            {
                "datastage_name": "canonical-pages",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/canonical/page.schema.json",
                "s3_path": "s3://112-canonical-final/BNF/lepji/pages/lepji-1889/lepji-1889-12-13-a-pages.jsonl.bz2"
            },
            {
                "datastage_name": "rebuilt",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/rebuilt/paper_contentitem.schema.json",
                "s3_path": "s3://122-rebuilt-final/BNF/lepji/lepji-1889.jsonl.bz2"
            }
        ],
        "semantic_enrichments": [
            {
                "datastage_name": "emb-words",
                "datastage_schema_link": "TODO",
                "s3_path": "s3://42-processed-data-final/embeddings/words/legacy-wemb002/"
            },
            {
                "datastage_name": "emb-docs",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/embeddings/embeddings-docs.schema.json",
                "s3_path": "s3://141-processed-data-staging/embeddings/docs/embeddings_gte_v1-1-0/BNF/lepji/lepji-1889.jsonl.bz2"
            },
            {
                "datastage_name": "emb-images-clip",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/image_embeddings/image_embeddings.schema.json",
                "s3_path": "s3://141-processed-data-staging/embeddings/images/embeddings_openclip_v1-0-0/BNF/lepji/lepji-1889-image-embeddings.jsonl.bz2"
            },
            {
                "datastage_name": "emb-images-dino",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/image_embeddings/image_embeddings.schema.json",
                "s3_path": "s3://141-processed-data-staging/embeddings/images/embeddings_dinov2_v1-0-0/BNF/lepji/lepji-1889-image-embeddings.jsonl.bz2"
            },
            {
                "datastage_name": "entities",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/entities/entities.schema.json",
                "s3_path": "s3://141-processed-data-staging/entities/entities-bert-historic-multilingual_fil-pers-loc-birth-org_v4-0-6/BNF/lepji/lepji-1889.jsonl.bz2"
            },
            {
                "datastage_name": "newsagencies",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/entities/entities.schema.json",
                "s3_path": "s3://141-processed-data-staging/newsagencies/newsagencies-bert-base-historic-multilingual_v1-0-0/BNF/lepji/lepji-1889.jsonl.bz2"
            },
            {
                "datastage_name": "langident",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/language_identification/language_identification.schema.json",
                "s3_path": "s3://141-processed-data-staging/langident/langident-lid-ensemble_multilingual_v2-0-0/lepji/lepji-1889.jsonl.bz2"
            },
            {
                "datastage_name": "lingproc",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/linguistic_annotation/lingproc.v2.schema.json",
                "s3_path": "s3://141-processed-data-staging/lingproc/*/lepji/lepji-1889.jsonl.bz2"
            },
            {
                "datastage_name": "ocrqa",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/ocr_qa/ocr_qa.schema.json",
                "s3_path": "s3://42-processed-data-final/ocrqa/ocrqa-ocrqa-wp_v1.0.6_v1-0-1/lepji/lepji-1889.jsonl.bz2"
            },
            {
                "datastage_name": "textreuse-passages",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/text_reuse/passage.schema.json",
                "s3_path": "s3://42-processed-data-final/textreuse/textreuse_passim_v1-0-0/results/tr_passages/lepji/tr_passages-lepji-1889.jsonl.bz2"
            },
            {
                "datastage_name": "textreuse-clusters",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/text_reuse/cluster.schema.json",
                "s3_path": "s3://42-processed-data-final/textreuse/textreuse_passim_v1-0-0/results/tr_clusters/"
            },
            {
                "datastage_name": "textreuse-index",
                "datastage_schema_link": "TODO",
                "s3_path": "s3://42-processed-data-final/textreuse/textreuse_passim_v1-0-0/results/tr_doc_cluster_index/lepji/tr_doc_cluster_index-lepji-1889.jsonl.bz2"
            },
            {
                "datastage_name": "topic-assignments",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/topic_model/topic_assignment.v2.schema.json",
                "s3_path": "s3://42-processed-data-final/topics/topics-tm-mallet_infer_seed42_v2.0.1-multilingual_v2-0-1/lepji/lepji-1889.jsonl.bz2"
            },
            {
                "datastage_name": "topics",
                "datastage_schema_link": "https://github.com/impresso/impresso-schemas/blob/master/json/topic_model/topic_description.schema.json",
                "s3_path": [
                    "s3://42-processed-data-final/topics/topics-tm-mallet_infer_seed42_v2.0.1-multilingual_v2-0-1/tm-de-all-v2.0.topic_model_topic_description.jsonl.bz2",
                    "s3://42-processed-data-final/topics/topics-tm-mallet_infer_seed42_v2.0.1-multilingual_v2-0-1/tm-fr-all-v2.0.topic_model_topic_description.jsonl.bz2",
                    "s3://42-processed-data-final/topics/topics-tm-mallet_infer_seed42_v2.0.1-multilingual_v2-0-1/tm-lb-all-v2.1.topic_model_topic_description.jsonl.bz2"
                ]
            }
        ]
    }
}
