=== impresso/impresso-schemas/json/entities/entities.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://impresso.github.io/impresso-schemas/json/entities/entities.schema.json",
  "title": "Named Entity JSON Schema",
  "description": "Definition of the output representation of entity processing, before indexing. Named entity mentions are expressed as offline annotations with character offsets relative to content items. Essentially, the NE output is a list of JSON documents (in json line format), where each document corresponds to a content item that has a list of NE mentions (no output for CI with no mentions). The tagset corresponds to impresso-HIPE.",
  "type": "object",
  "properties": {
    "ci_id": {
      "type": "string",
      "description": "Impresso content item ID."
    },
    "ci_type": {
      "type": "string",
      "description": "Impresso content item type."
    },
    "ts": {
      "type": "string",
      "description": "Timestamp of creation of the JSON file (e.g. '2024-05-26T09:48:01Z')."
    },
    "model_id": {
      "type": "string",
      "description": "An alias for the system or model that produced this output, used for transparency and traceability. It should include distinguishing elements like a base name, version, and language."
    },
    "nes": {
      "id": {
        "type": "string",
        "description": "The unique identifier of the named entity mention: [Document ID]:[Left Offset]:[Right Offset]:[Entity Type]:[NER Model]|[NEL Model]"
      },
      "type": "array",
      "description": "The list of named entity mentions identified in the document.",
      "minItems": 0,
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "description": "NE type (coarse-grained and fine-grained).",
            "enum": [
              "comp.demonym",
              "comp.function",
              "comp.name",
              "comp.qualifier",
              "comp.title",
              "loc",
              "loc.add.elec",
              "loc.add.phys",
              "loc.adm.nat",
              "loc.adm.reg",
              "loc.adm.sup",
              "loc.adm.town",
              "loc.fac",
              "loc.oro",
              "loc.phys.astro",
              "loc.phys.geo",
              "loc.phys.hydro",
              "loc.unk",
              "org",
              "org.adm",
              "org.ent",
              "org.ent.pressagency",
              "pers",
              "pers.coll",
              "pers.ind",
              "pers.ind.articleauthor",
              "prod",
              "prod.doctr",
              "prod.media",
              "time",
              "time.date.abs",
              "time.hour.abs",
              "org.ent.pressagency.Reuters",
              "org.ent.pressagency.Stefani",
              "org.ent.pressagency.Extel",
              "org.ent.pressagency.Havas",
              "org.ent.pressagency.Xinhua",
              "org.ent.pressagency.Domei",
              "org.ent.pressagency.Belga",
              "org.ent.pressagency.CTK",
              "org.ent.pressagency.ANSA",
              "org.ent.pressagency.DNB",
              "pers.ind.articleauthor",
              "org.ent.pressagency.Wolff",
              "org.ent.pressagency.unk",
              "org.ent.pressagency.UP-UPI",
              "org.ent.pressagency.ATS-SDA",
              "org.ent.pressagency.DPA",
              "org.ent.pressagency.AFP",
              "pers.ind.articleauthor",
              "org.ent.pressagency.Kipa",
              "org.ent.pressagency.ag",
              "org.ent.pressagency.Extel",
              "org.ent.pressagency.ATS-SDA",
              "org.ent.pressagency.Havas",
              "org.ent.pressagency.Reuters",
              "org.ent.pressagency.Xinhua",
              "org.ent.pressagency.AP",
              "org.ent.pressagency.APA",
              "org.ent.pressagency.ANSA",
              "org.ent.pressagency.DDP-DAPD",
              "org.ent.pressagency.TASS",
              "org.ent.pressagency.Europapress",
              "org.ent.pressagency.SPK-SMP",
              "unk"
            ]
          },
          "surface": {
            "type": "string",
            "description": "The surface form of the named entity mention, as it appears in the text."
          },
          "lOffset": {
            "type": "integer",
            "description": "The left character offset of the named entity with respect to the content item."
          },
          "rOffset": {
            "type": "integer",
            "description": "The right character offset of the named entity with respect to the content item."
          },
          "confidence_ner": {
            "type": "number",
            "description": "Confidence score of the Named Entity Recognition process."
          },
          "confidence_nel": {
            "type": "number",
            "description": "Confidence score of the Named Entity Linking process."
          },
          "wkd_id": {
            "type": "string",
            "description": "Wikidata QID if available."
          },
          "wkpedia_pagename": {
            "type": "string",
            "description": "Wikipedia page name, i.e. the last part of the wikipedia URL (e.g.  United_States)"
          },
          "wkpedia_url": {
            "type": "string",
            "description": "Wikipedia page URL, e.g. https://en.wikipedia.org/wiki/United_States"
          },
          "name": {
            "type": "string",
            "description": "In case of a person mention, the entity component of type 'name', as defined in the Impresso HIPE NE Annotation guidelines (https://zenodo.org/records/3585750)."
          },
          "title": {
            "type": "string",
            "description": "In case of a person mention, the entity component of type 'title', as defined in the Impresso HIPE NE Annotation guidelines (https://zenodo.org/records/3585750). "
          },
          "function": {
            "type": "string",
            "description": "In case of a person mention, the entity component of type 'function', as defined in the Impresso HIPE NE Annotation guidelines (https://zenodo.org/records/3585750). "
          }
        },
        "required": ["id", "type", "surface", "lOffset", "rOffset"]
      }
    }
  },
  "required": ["ci_id", "ts", "model_id", "nes"]
}

=== impresso/impresso-schemas/examples/entities/example0.json
{
  "ci_id": "EXP-1888-01-09-a-i0035",
  "ts": "2019-10-17T11:49:50Z",
  "model_id": "bert-fr",
  "nes": [
    {
      "type": "org.adm",
      "surface": "Société suisse du Grutli",
      "lOffset": 32,
      "rOffset": 56,
      "name": "Société suisse du Grutli",
      "wkd_id": "Q683672",
      "wkpedia_pagename": "Société_du_Grütli",
      "wkpedia_url": "https://fr.wikipedia.org/wiki/Soci%C3%A9t%C3%A9_du_Gr%C3%BCtli",
      "confidence_ner": 50.45,
      "confidence_nel": 50.45,
      "id": "EXP-1888-01-09-a-i0035:32:56:org.adm:bert-fr"
    },
    {
      "type": "pers.ind",
      "surface": "Mr. Bovat, mécanicien à Echallens",
      "lOffset": 156,
      "rOffset": 178,
      "wkd_id": "NIL",
      "wkpedia_pagename": "NIL",
      "wkpedia_url": "N/A",
      "confidence_ner": 50.45,
      "confidence_nel": 50.45,
      "name": "Bovat",
      "title": "Mr.",
      "function": "mécanicien à Echallens",
      "id": "EXP-1888-01-09-a-i0035:156:178:pers.ind:bert-fr"
    }
  ]
}

=== impresso/impresso-schemas/examples/entities/example2.json
{
  "ci_id": "EXP-1968-02-23-a-i0262",
  "ts": "2019-10-17T11:49:50Z",
  "model_id": "bert-fr",
  "nes": [
    {
      "type": "pers.ind",
      "surface": "championne de France de ski nautique, Sylvie Maurial",
      "lOffset": 50,
      "rOffset": 102,
      "confidence_ner": 50.45,
      "confidence_nel": 50.45,
      "wkd_id": "Q20993704",
      "wkpedia_pagename": "Sylvie_Maurial",
      "wkpedia_url": "https://fr.wikipedia.org/wiki/Sylvie_Maurial",
      "name": "Sylvie Maurial",
      "function": "championne de France de ski nautique",
      "id": "EXP-1968-02-23-a-i0262:50:102:pers.ind:bert-fr"
    },
    {
      "type": "loc.adm.nat",
      "surface": "France",
      "lOffset": 64,
      "rOffset": 70,
      "wkd_id": "Q20993704",
      "wkpedia_pagename": "France",
      "wkpedia_url": "https://fr.wikipedia.org/wiki/France",
      "confidence_ner": 50.45,
      "confidence_nel": 50.45,
      "id": "EXP-1888-01-09-a-i0035:64:70:loc.adm.nat:bert-fr"
    }
  ]
}

=== impresso/impresso-schemas/examples/entities/example1.json
{
  "ci_id": "EXP-1928-05-15-a-i0009",
  "ts": "2019-10-17T11:49:50Z",
  "model_id": "bert-fr",
  "nes": [
    {
      "id": "EXP-1928-05-15-a-i0009:50:99:pers.ind:bert-fr",
      "type": "pers.ind",
      "surface": "M. Wou, ancien ministre du gouvernement cantonais",
      "lOffset": 50,
      "rOffset": 99,
      "name": "Wou",
      "title": "M.",
      "function": "ancien ministre du gouvernement cantonais",
      "wkd_id": "NIL",
      "wkpedia_pagename": "NIL",
      "wkpedia_url": "N/A",
      "confidence_ner": 50.45,
      "confidence_nel": 50.45
    },
    {
      "id": "EXP-1888-01-09-a-i0035:32:42:loc.adm.nat:bert-fr",
      "type": "loc.adm.nat",
      "surface": "Etats-Unis",
      "lOffset": 32,
      "rOffset": 42,
      "wkd_id": "Q30",
      "wkpedia_pagename": "États-Unis",
      "wkpedia_url": "https://fr.wikipedia.org/wiki/%C3%89tats-Unis",
      "confidence_ner": 50.45,
      "confidence_nel": 50.45
    }
  ]
}
