=== impresso/impresso-schemas/json/image_embeddings/image_embeddings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://impresso.github.io/impresso-schemas/json/image_embeddings/image_embeddings.schema.json",
  "title": "Image Embeddings JSON Schema",
  "description": "A representation for the vector embedding representation of the content-items of type image.",
  "type": "object",
  "properties": {
    "ci_id": {
      "type": "string",
      "description": "Unique identifier for the content item.",
      "pattern": "^[a-zA-Z0-9]+-\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])-[a-z]-i\\d{4}$",
      "examples": ["actionfem-1940-01-08-a-i0001"]
    },
    "ts": {
      "type": "string",
      "description": "Timestamp indicating when the embedding was created (e.g., '2024-10-09T09:29:02Z').",
      "format": "date-time"
    },
    "model_id": {
      "type": "string",
      "description": "The ID of the model that produced this output, composed as specified in these slides: https://docs.google.com/presentation/d/1wH4LygLcT28rvMA82k5fyEyzdX49inGkqCLnBNZsFaw/edit#slide=id.g30cf04393c4_1_46.",
      "examples": ["emb-images_dinov2-v0.0.1"]
    },
    "size": {
      "type": "integer",
      "description": "The size of the embedding vector."
    },
    "embedding": {
      "oneOf": [
        {
          "type": "array",
          "description": "The vector embedding representation of the content item as a single list.",
          "items": {
            "type": "number",
            "description": "A single number in the vector embedding of the document.",
            "examples": [-0.732441]
          }
        }
      ]
    },
    "seconds": {
      "type": "number",
      "description": "Number of seconds it took to generate the embedding for this image.",
      "examples": [0.973115]
    },
    "title_year": {
      "type": "string",
      "description": "Title-year key this image emebeddings corresponds to.",
      "pattern": "^[a-zA-Z0-9]+-\\d{4}$",
      "examples": ["actionfem-1940"]
    }
  },
  "required": ["ci_id", "embedding", "model_id", "size"]
}

=== impresso/impresso-schemas/examples/image_embeddings/image_emendding_example.json
{
    "ci_id": "actionfem-1927-12-15-a-i0018",
    "ts": "2024-12-03T12:49:04Z",
    "model_id": "emb-images_dinov2-v0.0.1",
    "size": 1024,
    "embedding": [
        -0.732441,
        -1.115774,
        0.157154,
        0.750161,
        -2.174204,
        1.017714,
        -1.376679,
        1.263916,
        1.486546,
        -0.226359,
        -1.075212,
        -0.62178,
        -1.50876,
        -0.274806,
        1.225722,
        -0.842727,
        -0.039538,
        -2.167069,
        2.387333,
        -1.572418,
        -0.21925,
        0.457583,
        -1.045015,
        -2.800019,
        -1.26716,
        -1.706941,
        1.640146,
        -0.147903,
        -0.848617,
        0.653579,
        -0.595135,
        -0.465205,
        -1.384214,
        0.047901,
        -0.362822,
        -2.76938,
        0.287617,
        -0.678805,
        -2.028284,
        3.03757,
        -3.037702,
        -0.006154,
        -0.075637,
        1.759864,
        0.580912,
        -0.270187,
        0.53221,
        2.869359,
        1.791783,
        -1.155047,
        -0.024137,
        0.064696,
        -0.230076,
        -3.046477,
        0.528722,
        0.553314,
        -2.132393,
        2.399465,
        1.57475,
        0.754573,
        2.092841,
        -0.929662,
        0.976571,
        -0.520349,
        1.828344,
        -1.00422,
        -1.276266,
        -1.697545,
        0.882487,
        0.240259,
        -3.302628,
        -0.842299,
        0.588848,
        1.973981,
        -0.50072,
        -2.923492,
        4.51198,
        -0.933278,
        1.042628,
        2.134432,
        -0.516586,
        -1.085839,
        -0.403756,
        -0.957384,
        0.94782,
        -1.025428,
        -2.215712,
        -0.701926,
        -3.208735,
        -0.512471,
        0.775644,
        0.094858,
        -0.151586,
        -1.128582,
        2.702704,
        -0.307413,
        -0.148431,
        -0.24199,
        -1.010394,
        1.351347,
        0.849355,
        -1.492995,
        -1.225462,
        -0.913478,
        0.013756,
        0.47305,
        -1.210642,
        -1.767151,
        2.475919,
        0.386191,
        1.006306,
        0.390752,
        0.089344,
        -0.569013,
        -5.750748,
        1.375559,
        1.479498,
        -0.955723,
        -0.678785,
        1.425254,
        0.918163,
        -0.632367,
        1.269142,
        1.025191,
        0.486184,
        0.130338,
        0.211532,
        -1.569839,
        0.772326,
        -1.118332,
        2.709922,
        -1.91942,
        0.808285,
        -1.556616,
        -2.274686,
        -1.081229,
        -0.743757,
        -0.507114,
        -0.340417,
        0.843615,
        1.903843,
        1.441764,
        0.647131,
        0.606763,
        -0.296487,
        -0.560964,
        -0.652047,
        -0.998556,
        1.529885,
        -2.498847,
        0.685584,
        0.754791,
        0.599904,
        0.908863,
        1.233532,
        0.56376,
        1.34206,
        0.221583,
        -0.737967,
        0.071139,
        0.060377,
        3.055089,
        0.434888,
        -2.444624,
        0.776625,
        0.386977,
        0.471485,
        0.423088,
        -1.331506,
        1.911348,
        -1.614011,
        -0.658603,
        -0.408147,
        1.503188,
        0.641801,
        -0.577837,
        -1.215515,
        3.303419,
        -1.864808,
        -0.435096,
        0.575176,
        0.256906,
        1.118797,
        0.296573,
        -0.749811,
        2.694326,
        0.974681,
        -1.08708,
        0.680648,
        0.706602,
        1.721811,
        0.63904,
        -2.341784,
        -0.936717,
        0.585526,
        -0.743738,
        1.907259,
        0.367055,
        -0.569818,
        0.607363,
        -0.542823,
        0.732817,
        0.316059,
        0.677357,
        -0.010871,
        0.147661,
        2.017473,
        -1.578633,
        0.059942,
        -0.506129,
        -1.666601,
        2.529889,
        -0.525183,
        -1.383771,
        -0.233668,
        0.434117,
        -0.96799,
        1.191701,
        4.945845,
        -1.960644,
        -0.203692,
        -1.032683,
        -1.315461,
        -2.206836,
        -0.252644,
        0.355065,
        1.791385,
        1.856226,
        -1.795703,
        -0.061684,
        1.83339,
        0.172905,
        0.424624,
        -1.540377,
        -0.270438,
        1.259565,
        0.035455,
        0.999378,
        -0.577998,
        0.335947,
        -0.569971,
        -0.548833,
        -0.213044,
        -4.178254,
        2.335537,
        2.840181,
        -3.139968,
        1.334362,
        2.050022,
        -3.197975,
        0.75706,
        0.194177,
        -1.023799,
        0.295573,
        -0.845672,
        0.353218,
        -1.551787,
        1.096826,
        -0.743593,
        0.789702,
        1.712,
        0.338542,
        -2.899538,
        0.44341,
        -3.666357,
        1.230123,
        2.045952,
        0.504376,
        3.031221,
        -1.17657,
        -0.1271,
        -0.056142,
        -0.121323,
        -0.590975,
        0.53045,
        -2.125972,
        -0.601353,
        0.124178,
        1.662136,
        2.79051,
        0.696004,
        -1.146591,
        -2.086907,
        -0.339434,
        -0.175697,
        -0.581441,
        0.563717,
        -0.795408,
        -2.093136,
        -1.58388,
        -0.734077,
        1.589263,
        2.894493,
        -1.537023,
        -0.346928,
        1.403039,
        -0.910518,
        -0.1976,
        0.159671,
        2.015169,
        0.601524,
        -1.407861,
        -2.201485,
        0.84585,
        0.022624,
        1.698342,
        1.872136,
        0.236731,
        -0.223933,
        -2.195946,
        0.700871,
        1.548368,
        0.518677,
        0.51796,
        0.297642,
        0.884255,
        -2.264982,
        0.979358,
        -1.619088,
        -1.141478,
        1.038997,
        -0.361495,
        -0.446714,
        1.711344,
        1.015835,
        -0.62432,
        -0.478213,
        -0.683814,
        -0.171105,
        -0.799382,
        0.286178,
        1.479792,
        -0.905172,
        -0.840543,
        -1.48528,
        0.026739,
        2.550786,
        0.839745,
        1.143056,
        -1.52299,
        -1.611401,
        -0.14705,
        2.386418,
        -1.183945,
        -1.466908,
        0.16296,
        1.689574,
        1.457172,
        2.255874,
        -2.49649,
        0.117066,
        -1.286518,
        1.378593,
        0.241106,
        1.408327,
        -0.793933,
        -1.161135,
        -2.015491,
        -1.248117,
        2.80789,
        -0.823914,
        -2.339155,
        1.325308,
        2.351815,
        -0.994938,
        -1.900723,
        2.559785,
        1.141804,
        1.593699,
        1.18331,
        -0.399869,
        0.657,
        1.593488,
        0.637206,
        -0.083616,
        0.860518,
        1.077042,
        1.152307,
        0.297243,
        1.313153,
        -0.814114,
        0.478602,
        -0.042962,
        2.236318,
        1.696766,
        -2.27955,
        -0.463531,
        1.915208,
        1.803883,
        -1.383321,
        -1.619672,
        1.111633,
        -0.822998,
        -0.117846,
        0.502538,
        -2.111868,
        -0.222007,
        -0.240234,
        0.146221,
        0.039166,
        1.195226,
        -0.16752,
        -2.450662,
        0.589477,
        -0.728141,
        -0.879459,
        -0.244973,
        0.211559,
        -1.05788,
        -1.569758,
        -1.036393,
        -0.8069,
        -2.457829,
        0.121506,
        -1.891079,
        -0.320597,
        2.449431,
        -0.986316,
        -0.646131,
        0.125416,
        -0.928778,
        1.646997,
        0.814154,
        -2.053128,
        -1.42171,
        -1.452967,
        2.481934,
        -3.074021,
        -0.204183,
        0.3835,
        0.201851,
        -0.046606,
        1.145085,
        -0.767142,
        -0.679543,
        -1.831077,
        0.050853,
        2.741623,
        -0.720919,
        -0.591647,
        1.192285,
        -3.393137,
        -0.831244,
        -1.293201,
        -1.053614,
        -0.409675,
        -2.962971,
        -0.810893,
        0.845352,
        0.747864,
        -2.649103,
        0.179074,
        -0.296096,
        1.217795,
        1.528494,
        -4.300601,
        1.653121,
        -0.603403,
        3.495902,
        -0.035486,
        0.54033,
        0.862146,
        -2.780511,
        0.550174,
        -0.453092,
        0.516107,
        -1.42114,
        -0.531002,
        1.395289,
        1.556354,
        -1.180264,
        0.20422,
        0.867086,
        -1.600055,
        1.23501,
        0.595156,
        1.688627,
        -0.431991,
        -0.429611,
        -0.308876,
        -1.299333,
        -1.180786,
        0.460032,
        1.795619,
        -0.080593,
        2.157546,
        1.343401,
        3.632094,
        0.053602,
        0.831005,
        -0.692584,
        -2.508076,
        1.923033,
        1.774251,
        -1.207638,
        -1.405938,
        -0.833917,
        -0.109989,
        -0.077119,
        -1.206213,
        1.395631,
        -0.379884,
        0.278636,
        -1.574244,
        -1.01546,
        -0.574205,
        0.225085,
        1.762447,
        1.871033,
        0.743401,
        -1.58269,
        -0.660398,
        -0.610974,
        0.130164,
        -2.386864,
        -0.05142,
        1.098557,
        -1.251668,
        0.920495,
        0.113644,
        0.427675,
        -0.06352,
        -1.573662,
        -1.019431,
        -1.572071,
        -0.885534,
        2.170498,
        -0.964411,
        -0.038217,
        3.119871,
        0.146253,
        -2.920377,
        1.28526,
        2.768594,
