=== impresso/impresso-schemas/json/text_reuse/cluster.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://impresso.github.io/impresso-schemas/json/text_reuse/cluster.schema.json",
  "title": "Text-Reuse Cluster",
  "description": "A cluster of text reuse passages sharing common content across different newspaper issues.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier for this cluster.",
      "examples": ["tr-all-v1-24-c600067"]
    },
    "min_date": {
      "type": "string",
      "description": "Earliest date represented in the article passages of the cluster",
      "pattern": "^(\\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$"
    },
    "max_date": {
      "type": "string",
      "description": "Latest date represented in the article passages of the cluster",
      "pattern": "^(\\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$"
    },
    "cluster_size": {
      "type": "integer",
      "description": "Number of article passages present in the cluster."
    },
    "time_delta": {
      "type": "integer",
      "description": "Number of days between min_date and max_date."
    },
    "newspapers": {
      "type": "array",
      "description": "List of all newspapers represented in this cluster with article passages.",
      "items": {
        "type": "string"
      }
    },
    "passages": {
      "type": "array",
      "description": "List of all article passages composing this cluster.",
      "items": {
        "type": "string",
        "description": "One article passage, defined by its content-item ID, followed by '@' and the start and end indices of the passage separated by ':'.",
        "pattern": "^[a-zA-Z0-9]+-\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])-[a-z]-i\\d{4}@\\d+:\\d+$",
        "examples": ["JDG-1991-11-01-a-i0153@3285:3768"]
      }
    },
    "doc_ids": {
      "type": "array",
      "description": "List of all article passages composing this cluster.",
      "items": {
        "type": "string",
        "description": "One article passage, defined by its content-item ID, followed by '@' and the start and end indices of the passage separated by ':'.",
        "pattern": "^[a-zA-Z0-9]+-\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])-[a-z]-i\\d{4}$",
        "examples": ["JDG-1991-11-01-a-i0153"]
      }
    },
    "lexical_overlap": {
      "type": "number",
      "description": "Computed average lexical overlap of the passages within the cluster."
    }
  },
  "required": [
    "id",
    "min_date",
    "max_date",
    "cluster_size",
    "time_delta",
    "newspapers",
    "passages",
    "doc_ids",
    "lexical_overlap"
  ]
}

=== impresso/impresso-schemas/examples/text_reuse/tr_cluster_example.json
{
  "id": "tr-all-v1-24-c25770444430",
  "min_date": "2014-12-04",
  "max_date": "2015-11-03",
  "cluster_size": 2,
  "time_delta": 334,
  "newspapers": ["EXP", "IMP"],
  "passages": ["IMP-2014-12-04-a-i0049@203:410", "EXP-2015-11-03-a-i0035@5348:5593"],
  "doc_ids": ["EXP-2015-11-03-a-i0035", "IMP-2014-12-04-a-i0049"],
  "lexical_overlap": 65.71428571428571
}
