=== impresso/impresso-schemas/json/text_reuse/passage.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://impresso.github.io/impresso-schemas/json/text_reuse/passage.schema.json",
  "title": "Text-Reuse Passage",
  "description": "A single passage (span of text) that is part of a text reuse cluster.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier for this passage.",
      "pattern": "^c\\d+-[a-zA-Z0-9]+-\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])-[a-z]-i\\d{4}@\\d+:\\d+$",
      "examples": ["c68720283542-armeteufel-1904-08-07-a-i0010@8067:8460"]
    },
    "begin": {
      "type": "integer",
      "description": "Start index of the text-reuse passage within the article"
    },
    "ci_id": {
      "type": "string",
      "description": "Content-item ID this passage is from.",
      "pattern": "^[a-zA-Z0-9]+-\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])-[a-z]-i\\d{4}$",
      "examples": ["armeteufel-1904-08-07-a-i0010"]
    },
    "cluster_id": {
      "type": "string",
      "description": "Unique identifier for this passage's cluster.",
      "examples": ["tr-all-v1-24-c68720283542"]
    },
    "date": {
      "type": "string",
      "description": "Date of publication of the issue in which the passage appears.",
      "pattern": "^(\\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$"
    },
    "end": {
      "type": "integer",
      "description": "End index of the text-reuse passage within the article"
    },
    "pages": {
      "type": "array",
      "description": "Pages content, with id, seq and regions it corresponds to."
    },
    "cluster_size": {
      "type": "integer",
      "description": "Number of passages in this passage's cluster."
    },
    "text": {
      "type": "string",
      "description": "Full text of the passage."
    },
    "title": {
      "type": "string",
      "description": "Title of the article this passage is from."
    },
    "type": {
      "type": "string",
      "description": "Type of the article the passage is from (Not in this release)."
    },
    "cluster_time_delta": {
      "type": "integer",
      "description": "Number of days between min_date and max_date."
    },
    "cluster_lexical_overlap": {
      "type": "number",
      "description": "Computed average lexical overlap of the passages within the cluster. Note these was a mistake in the last processing and this key might be `cluster_lexial_overlap`."
    },
    "connected_clusters": {
      "type": "array",
      "description": "List of clusters also with passages present in this content-item."
    },
    "n_connected_clusters": {
      "type": "integer",
      "description": "Number of connected_clusters for this content-item."
    }
  },
  "required": [
    "id",
    "begin",
    "ci_id",
    "cluster_id",
    "date",
    "end",
    "cluster_size",
    "text",
    "title",
    "cluster_time_delta",
    "cluster_lexical_overlap",
    "connected_clusters",
    "n_connected_clusters"
  ]
}

=== impresso/impresso-schemas/examples/text_reuse/tr_passage_example.json
{
  "id": "c81238-EXP-1976-10-08-a-i0176@0:386",
  "begin": 0,
  "ci_id": "EXP-1976-10-08-a-i0176",
  "cluster_id": "tr-all-v1-24-c81238",
  "date": "1976-10-08",
  "end": 386,
  "pages": [
    {
      "id": "EXP-1976-10-08-a-p0008",
      "seq": 8,
      "regions": [
        {
          "start": 0,
          "length": 386,
          "coords": {
            "x": 621,
            "y": 1564,
            "w": 555,
            "h": 274
          }
        }
      ]
    }
  ],
  "cluster_size": 76,
  "text": "BANQUE CANTONALE NEUCH\u00c2TELOISE\ncherche pour son si\u00e8ge de Neuch\u00e2tel\nRESPONSABLE\npour son SERVICE EXP\u00c9DITION\nayant si possible quelques ann\u00e9es de pratique et poss\u00e9dant un permis de\nconduire.\nEntr\u00e9e en fonction d\u00e8s que possible.\nEmploi stable avec les avantages sociaux d'une grande entreprise.\nFaire offres \u00e9crites avec documents d'usage au Service du personnel de la\nBCN-2001 Neuch\u00e2tel.\n",
  "title": "",
  "cluster_time_delta": 4590,
  "cluster_lexical_overlap": 3.3707865168539324,
  "connected_clusters": ["tr-all-v1-24-c81238"],
  "n_connected_clusters": 1
}
